// ─────────────────────────────────────────────────────────────────────────────
// session-data.js  —  Single source of truth for all ICET alumni session data
// To add a new session: add an entry here with active:true and populate members.
// ─────────────────────────────────────────────────────────────────────────────

export const SESSION_DATA = {

  // ── Active sessions ──────────────────────────────────────────────────────
  '2006': {
    label: 'Session 2006–2010',
    total: 187, morning: 124, evening: 63,
    whatsapp: '',   // paste group invite link here when available
    active: true,
    members: [
      {"roll":"CE-M6-101","name":"ABDUL WAHAB KHAN","shift":"Morning"},
      {"roll":"CE-M6-102","name":"ZAHID ANJUM","shift":"Morning"},
      {"roll":"CE-M6-103","name":"USMAN RAFIQ","shift":"Morning"},
      {"roll":"CE-M6-104","name":"MEESAM ALI","shift":"Morning"},
      {"roll":"CE-M6-105","name":"IRFAN IQBAL","shift":"Morning"},
      {"roll":"CE-M6-106","name":"WASEEM SAFDAR","shift":"Morning"},
      {"roll":"CE-M6-107","name":"NASEER AHMAD","shift":"Morning"},
      {"roll":"CE-M6-108","name":"RIZWAN HAIDER","shift":"Morning"},
      {"roll":"CE-M6-109","name":"UMAR FAROOQ","shift":"Morning"},
      {"roll":"CE-M6-110","name":"MUHAMMAD FIAZ","shift":"Morning"},
      {"roll":"CE-M6-111","name":"FAROOQ KHAN","shift":"Morning"},
      {"roll":"CE-M6-112","name":"SALMAN SIDIQUE","shift":"Morning"},
      {"roll":"CE-M6-113","name":"HAFIZ AAMIR","shift":"Morning"},
      {"roll":"CE-M6-114","name":"MOHSIN ALI RAZA","shift":"Morning"},
      {"roll":"CE-M6-115","name":"MUHAMMAD KASHIF","shift":"Morning"},
      {"roll":"CE-M6-116","name":"RIZWAN GHULAM NABI","shift":"Morning"},
      {"roll":"CE-M6-117","name":"AYAZ KARIM","shift":"Morning"},
      {"roll":"CE-M6-118","name":"ADEEM GHAFFAR RANA","shift":"Morning"},
      {"roll":"CE-M6-119","name":"KHIZAR HAYAT","shift":"Morning"},
      {"roll":"CE-M6-120","name":"AWAIS NADEEM","shift":"Morning"},
      {"roll":"CE-M6-121","name":"SAQIB WAHEED","shift":"Morning"},
      {"roll":"CE-M6-122","name":"RAO SHAFIQ","shift":"Morning"},
      {"roll":"CE-M6-123","name":"FAYYAZ AHMAD","shift":"Morning"},
      {"roll":"CE-M6-124","name":"KHUBAIB HASAN","shift":"Morning"},
      {"roll":"CE-M6-125","name":"TAHIR NAZIR","shift":"Morning"},
      {"roll":"CE-M6-126","name":"MANSAB ALI","shift":"Morning"},
      {"roll":"CE-M6-127","name":"ZAHID RASOOL","shift":"Morning"},
      {"roll":"CE-M6-128","name":"UMAIR ISLAM","shift":"Morning"},
      {"roll":"CE-M6-129","name":"ZOHAIB ZAIDI","shift":"Morning"},
      {"roll":"CE-M6-130","name":"ASAD ABBAS","shift":"Morning"},
      {"roll":"CE-M6-131","name":"AJMAL JAVAID","shift":"Morning"},
      {"roll":"CE-M6-132","name":"KHALIL AHMAD","shift":"Morning"},
      {"roll":"CE-M6-133","name":"WAQAS AZIZ HASHMI","shift":"Morning"},
      {"roll":"CE-M6-134","name":"AFZAL CAUDHRY","shift":"Morning"},
      {"roll":"CE-M6-135","name":"MUJEEB UR REHMAN","shift":"Morning"},
      {"roll":"CE-M6-136","name":"ALI BUKHARI","shift":"Morning"},
      {"roll":"CE-M6-137","name":"AWAIS NAEEM","shift":"Morning"},
      {"roll":"CE-M6-138","name":"SAAD TOOR","shift":"Morning"},
      {"roll":"CE-M6-139","name":"KASHIF YOUNIS","shift":"Morning"},
      {"roll":"CE-M6-140","name":"AFFAN KHALID","shift":"Morning"},
      {"roll":"CE-M6-141","name":"JAHENZAIB KHAN","shift":"Morning"},
      {"roll":"CE-M6-142","name":"AHSAN BILAL","shift":"Morning"},
      {"roll":"CE-M6-143","name":"SAQIB RIZVI","shift":"Morning"},
      {"roll":"CE-M6-144","name":"SYED MUHAMMAD QAISER KHAN","shift":"Morning"},
      {"roll":"CE-M6-145","name":"UMAIR RASHEED","shift":"Morning"},
      {"roll":"CE-M6-146","name":"ALI NADEEM","shift":"Morning"},
      {"roll":"CE-M6-147","name":"FAWAD FURRUKH","shift":"Morning"},
      {"roll":"CE-M6-148","name":"AFNAN HAMEED","shift":"Morning"},
      {"roll":"CE-M6-149","name":"ABDUL REHMAN","shift":"Morning"},
      {"roll":"CE-M6-150","name":"IBRAHIM SAEED","shift":"Morning"},
      {"roll":"CE-M6-151","name":"MUHAMMA ARIF KHAN","shift":"Morning"},
      {"roll":"CE-M6-152","name":"MUHAMMAD HARIS","shift":"Morning"},
      {"roll":"CE-M6-153","name":"IMRAN KHAN","shift":"Morning"},
      {"roll":"CE-M6-154","name":"NOUMAN AHMAD","shift":"Morning"},
      {"roll":"CE-M6-155","name":"IMRAN KHAN","shift":"Morning"},
      {"roll":"CE-M6-156","name":"JAMSHAID IQBAL","shift":"Morning"},
      {"roll":"CE-M6-157","name":"FAISAL MEHMOOD","shift":"Morning"},
      {"roll":"CE-M6-158","name":"SHERAZ AFZAL","shift":"Morning"},
      {"roll":"CE-M6-159","name":"ADNAN SHOAIB","shift":"Morning"},
      {"roll":"CE-M6-160","name":"KARIM BUKSH","shift":"Morning"},
      {"roll":"CE-M6-161","name":"UMAIR DANISH","shift":"Morning"},
      {"roll":"CE-M6-162","name":"AAMIR SHAMAS","shift":"Morning"},
      {"roll":"CE-M6-163","name":"WAZIR ALI","shift":"Morning"},
      {"roll":"CE-M6-164","name":"JAMA AHMAD HERSI","shift":"Morning"},
      {"roll":"PG-M6-201","name":"TAYAB SAEED","shift":"Morning"},
      {"roll":"PG-M6-202","name":"ATIF ASHRAF","shift":"Morning"},
      {"roll":"PG-M6-203","name":"ASAD ALI","shift":"Morning"},
      {"roll":"PG-M6-204","name":"NAVEED AKHTAR","shift":"Morning"},
      {"roll":"PG-M6-205","name":"MUNZOOR AHMAD","shift":"Morning"},
      {"roll":"PG-M6-206","name":"FARAZ BUTT","shift":"Morning"},
      {"roll":"PG-M6-207","name":"SANA ULLAH","shift":"Morning"},
      {"roll":"PG-M6-208","name":"BABER ALI","shift":"Morning"},
      {"roll":"PG-M6-209","name":"AAMIR RIAZ","shift":"Morning"},
      {"roll":"PG-M6-210","name":"GHULAM ABBAS","shift":"Morning"},
      {"roll":"PG-M6-211","name":"MUHAMMAD BASIT ALI","shift":"Morning"},
      {"roll":"PG-M6-212","name":"ZEESHAN SHOAIB","shift":"Morning"},
      {"roll":"PG-M6-213","name":"MUHAMMAD KALEEM ULLAH","shift":"Morning"},
      {"roll":"PG-M6-214","name":"HAFIZ KHALIL UR REHMAN","shift":"Morning"},
      {"roll":"PG-M6-215","name":"FAISAL JOYIA","shift":"Morning"},
      {"roll":"PG-M6-216","name":"FAISAL KHALIL","shift":"Morning"},
      {"roll":"PG-M6-217","name":"MUHAMMAD ZEESHAN SALEEM","shift":"Morning"},
      {"roll":"PG-M6-218","name":"AHSAN NOOR KHAN","shift":"Morning"},
      {"roll":"PG-M6-219","name":"WAQAS SHEHRYAR","shift":"Morning"},
      {"roll":"PG-M6-220","name":"AFTAB AHMAD","shift":"Morning"},
      {"roll":"PG-M6-221","name":"TANVIR AHMAD","shift":"Morning"},
      {"roll":"PG-M6-222","name":"FAKHAR ABBAS","shift":"Morning"},
      {"roll":"PG-M6-223","name":"MUHAMMAD  HASNAT ALI","shift":"Morning"},
      {"roll":"PG-M6-224","name":"YASIR ARAFAT","shift":"Morning"},
      {"roll":"PG-M6-225","name":"TAHIR WASIM","shift":"Morning"},
      {"roll":"PG-M6-226","name":"MOHSIN SAEED","shift":"Morning"},
      {"roll":"BC-M6-301","name":"SAEED AKRAM SHEIKH","shift":"Morning"},
      {"roll":"BC-M6-302","name":"IMRAN YOUSAF","shift":"Morning"},
      {"roll":"BC-M6-303","name":"MUHAMMAD ADNAN SADIQ","shift":"Morning"},
      {"roll":"BC-M6-304","name":"MUHAMMAD IRFAN","shift":"Morning"},
      {"roll":"BC-M6-305","name":"IMRAN RIAZ","shift":"Morning"},
      {"roll":"BC-M6-306","name":"NASIR MEHMOOD","shift":"Morning"},
      {"roll":"BC-M6-307","name":"SHAMSHAD-UL-HAQ","shift":"Morning"},
      {"roll":"BC-M6-308","name":"AWAIS ABDULLAH","shift":"Morning"},
      {"roll":"BC-M6-309","name":"UMAIR AZAD","shift":"Morning"},
      {"roll":"BC-M6-310","name":"ALI ZULQARNAIN","shift":"Morning"},
      {"roll":"BC-M6-311","name":"MUHAMMAD RIZWAN AZHAR","shift":"Morning"},
      {"roll":"BC-M6-312","name":"MUHAMMAD ASAD MASOOD","shift":"Morning"},
      {"roll":"BC-M6-313","name":"HAFIZ SHAFIQ","shift":"Morning"},
      {"roll":"BC-M6-314","name":"HAFIZ ZUBAIR","shift":"Morning"},
      {"roll":"BC-M6-315","name":"MUHAMMAD NAEEM","shift":"Morning"},
      {"roll":"BC-M6-316","name":"GHUFRAN AHMAD","shift":"Morning"},
      {"roll":"BC-M6-317","name":"ABDUL LATIF","shift":"Morning"},
      {"roll":"EE-M6-401","name":"AMBREEN GHALIB","shift":"Morning"},
      {"roll":"EE-M6-402","name":"MUHAMMAD SHAHZAD ALI","shift":"Morning"},
      {"roll":"EE-M6-403","name":"MUHAMMAD ILYAS","shift":"Morning"},
      {"roll":"EE-M6-404","name":"YASIR SHARIF AWAN","shift":"Morning"},
      {"roll":"EE-M6-405","name":"RAO MUNEER ALI","shift":"Morning"},
      {"roll":"EE-M6-406","name":"SAJID MAHMOOD","shift":"Morning"},
      {"roll":"EE-M6-407","name":"ALI MURAD","shift":"Morning"},
      {"roll":"EE-M6-408","name":"USMAN ALI","shift":"Morning"},
      {"roll":"EE-M6-409","name":"MUHAMMAD AWAIS","shift":"Morning"},
      {"roll":"EE-M6-410","name":"AMBREEN GULZAR","shift":"Morning"},
      {"roll":"EE-M6-411","name":"FAHIM AHMAD ZAFAR","shift":"Morning"},
      {"roll":"EE-M6-412","name":"ANWAAR AHMAD","shift":"Morning"},
      {"roll":"EE-M6-413","name":"USMAN RASHEED","shift":"Morning"},
      {"roll":"EE-M6-414","name":"KHUBAIB AHMAD","shift":"Morning"},
      {"roll":"EE-M6-415","name":"SALMAN MANSOOR","shift":"Morning"},
      {"roll":"EE-M6-416","name":"USMAN SAEED","shift":"Morning"},
      {"roll":"EE-M6-417","name":"SADIA NAUREEN","shift":"Morning"},
      {"roll":"CE-E6-102","name":"FAHAD MASOOD","shift":"Evening"},
      {"roll":"CE-E6-103","name":"NOMAN LIAQAT","shift":"Evening"},
      {"roll":"CE-E6-104","name":"YASEEN AKRAM","shift":"Evening"},
      {"roll":"CE-E6-105","name":"ADNAN NAWAZ","shift":"Evening"},
      {"roll":"CE-E6-106","name":"AHSEN HAFEEZ","shift":"Evening"},
      {"roll":"CE-E6-107","name":"RAZA MUDASIR ALVI","shift":"Evening"},
      {"roll":"CE-E6-108","name":"GULZEB KHAN","shift":"Evening"},
      {"roll":"CE-E6-109","name":"USMAN SADIQUE","shift":"Evening"},
      {"roll":"CE-E6-110","name":"ABDUL QAYYUM","shift":"Evening"},
      {"roll":"CE-E6-111","name":"IMRAN MALIK","shift":"Evening"},
      {"roll":"CE-E6-112","name":"SHAHID NADEEM","shift":"Evening"},
      {"roll":"CE-E6-113","name":"UMAIR FURQAN","shift":"Evening"},
      {"roll":"CE-E6-114","name":"NAUMAN ASHRAF","shift":"Evening"},
      {"roll":"CE-E6-115","name":"WAQAS BUKHARI","shift":"Evening"},
      {"roll":"CE-E6-116","name":"SANA ULLAH","shift":"Evening"},
      {"roll":"CE-E6-117","name":"NAEEM YOUNIS","shift":"Evening"},
      {"roll":"CE-E6-118","name":"MASOOD HAIDER","shift":"Evening"},
      {"roll":"CE-E6-119","name":"MUHAMMAD ASIF KHAN","shift":"Evening"},
      {"roll":"CE-E6-120","name":"MOHSIN MOBEEN","shift":"Evening"},
      {"roll":"CE-E6-121","name":"FAHEEM RIAZ","shift":"Evening"},
      {"roll":"CE-E6-122","name":"FAHAD MIR","shift":"Evening"},
      {"roll":"CE-E6-123","name":"ADNAN REHMAT","shift":"Evening"},
      {"roll":"CE-E6-124","name":"YASIR AKRAM AWAN","shift":"Evening"},
      {"roll":"CE-E6-125","name":"SHAROOZ KHAN","shift":"Evening"},
      {"roll":"CE-E6-126","name":"RANA MUHAMMAD IMRAN","shift":"Evening"},
      {"roll":"CE-E6-127","name":"RIZWAN MALIK","shift":"Evening"},
      {"roll":"CE-E6-128","name":"UMER TAHIR MIR","shift":"Evening"},
      {"roll":"CE-E6-129","name":"MUHAMMAD NAEEM IQBAL","shift":"Evening"},
      {"roll":"CE-E6-130","name":"MUHAMMAD UMAIR DANISH","shift":"Evening"},
      {"roll":"CE-E6-131","name":"ABID ALI","shift":"Evening"},
      {"roll":"CE-E6-132","name":"FARHAN CHEEMA","shift":"Evening"},
      {"roll":"CE-E6-133","name":"MUHAMMAD ARSHAD","shift":"Evening"},
      {"roll":"CE-E6-134","name":"ZUBAIR SHAHID","shift":"Evening"},
      {"roll":"CE-E6-135","name":"WAQAR AHMED","shift":"Evening"},
      {"roll":"CE-E6-136","name":"AFFAN AHMAD","shift":"Evening"},
      {"roll":"CE-E6-137","name":"UMAIR SHOAIB","shift":"Evening"},
      {"roll":"CE-E6-138","name":"ARSALAN AWAN","shift":"Evening"},
      {"roll":"CE-E6-139","name":"MUHAMMAD IMRAN","shift":"Evening"},
      {"roll":"CE-E6-140","name":"ASIF IQBAL","shift":"Evening"},
      {"roll":"CE-E6-141","name":"HAKIM ALI HAIDER","shift":"Evening"},
      {"roll":"CE-E6-142","name":"GHULAM MURTAZA","shift":"Evening"},
      {"roll":"CE-E6-143","name":"ADNAN SALEEM","shift":"Evening"},
      {"roll":"CE-E6-144","name":"ASIF ALI SHAHZAD","shift":"Evening"},
      {"roll":"PG-E6-201","name":"MUHAMMAD ZAMAN","shift":"Evening"},
      {"roll":"PG-E6-202","name":"IMRAN NIAZ","shift":"Evening"},
      {"roll":"PG-E6-203","name":"SHAHID SAEED","shift":"Evening"},
      {"roll":"PG-E6-204","name":"KHURRAM JAVED","shift":"Evening"},
      {"roll":"PG-E6-205","name":"SAQIB RAZA","shift":"Evening"},
      {"roll":"PG-E6-206","name":"AAMIR KARIM","shift":"Evening"},
      {"roll":"PG-E6-207","name":"MUHAMMAD UMAR FAROOQ","shift":"Evening"},
      {"roll":"PG-E6-208","name":"ALI AHMAD","shift":"Evening"},
      {"roll":"PG-E6-209","name":"ABDUL BASIT","shift":"Evening"},
      {"roll":"PG-E6-210","name":"FARHAN RASOOL","shift":"Evening"},
      {"roll":"PG-E6-211","name":"NASEER AHMAD","shift":"Evening"},
      {"roll":"PG-E6-212","name":"MUHAMMAD USMAN","shift":"Evening"},
      {"roll":"PG-E6-213","name":"AQEEL MANSOOR CHISHTI","shift":"Evening"},
      {"roll":"PG-E6-214","name":"RIZWAN AHMED SHAH","shift":"Evening"},
      {"roll":"PG-E6-215","name":"MUAMMAD ZAIN","shift":"Evening"},
      {"roll":"PG-E6-216","name":"USMAN ANWAR DAR","shift":"Evening"},
      {"roll":"PG-E6-217","name":"OMER SHUJAT","shift":"Evening"},
      {"roll":"PG-E6-218","name":"IMRAN RAFIQUE","shift":"Evening"},
      {"roll":"PG-E6-219","name":"NAEEM BHATTI","shift":"Evening"},
      {"roll":"PG-E6-220","name":"ASIF SANI","shift":"Evening"}
    ]
  },

  '2009': {
    label: 'Session 2009–2013',
    total: 139, morning: 79, evening: 60,
    whatsapp: '',   // paste group invite link here when available
    active: true,
    members: [
      {"roll":"M09-10CE01","name":"KASHIF YASIN","shift":"Morning"},
      {"roll":"M09-10CE02","name":"SAJJAD HUSSAIN","shift":"Morning"},
      {"roll":"M09-10CE03","name":"ASIM GHAFOOR","shift":"Morning"},
      {"roll":"M09-10CE04","name":"ABDUL REHMAN","shift":"Morning"},
      {"roll":"M09-10CE05","name":"IMRAN SARWER","shift":"Morning"},
      {"roll":"M09-10CE06","name":"ADNAN ZUBAIR KHALID","shift":"Morning"},
      {"roll":"M09-10CE07","name":"MUHAMMAD SHAHID AMIN","shift":"Morning"},
      {"roll":"M09-10CE08","name":"WAQAS IQBAL","shift":"Morning"},
      {"roll":"M09-10CE09","name":"FAHID GHULAM RASOOL","shift":"Morning"},
      {"roll":"M09-10CE10","name":"NOMAN AHMAD","shift":"Morning"},
      {"roll":"M09-10CE11","name":"ARSALAN YASIN","shift":"Morning"},
      {"roll":"M09-10CE12","name":"MUHAMMAD WAQAS","shift":"Morning"},
      {"roll":"M09-10CE13","name":"SHEHROZE ALI","shift":"Morning"},
      {"roll":"M09-10CE14","name":"RAMEEZ ANWAR ANSARI","shift":"Morning"},
      {"roll":"M09-10CE15","name":"QAMMAR-U-DIN","shift":"Morning"},
      {"roll":"M09-10CE16","name":"SHABBIR RAZA ALI","shift":"Morning"},
      {"roll":"M09-10CE17","name":"BILAL HASSAN","shift":"Morning"},
      {"roll":"M09-10CE18","name":"SYED ALI MUSA KAZMI","shift":"Morning"},
      {"roll":"M09-10CE19","name":"ABUBAKAR SOHAIL","shift":"Morning"},
      {"roll":"M09-10CE20","name":"SOHAIB REHMAN","shift":"Morning"},
      {"roll":"M09-10CE21","name":"ABDUL SALAM","shift":"Morning"},
      {"roll":"M09-10CE22","name":"MUHAMMAD NADEEM","shift":"Morning"},
      {"roll":"M09-10CE23","name":"MUHAMMAD REHAN KHAN","shift":"Morning"},
      {"roll":"M09-10CE24","name":"AWAIS YOUNAS","shift":"Morning"},
      {"roll":"M09-10CE25","name":"UMAR SHEHZAD","shift":"Morning"},
      {"roll":"M09-10CE26","name":"MUHAMMAD USMAN LATIF","shift":"Morning"},
      {"roll":"M09-10CE27","name":"SUHAIL AHMED SHAH","shift":"Morning"},
      {"roll":"M09-10CE28","name":"MUHAMMAD AAMIR SHAHID","shift":"Morning"},
      {"roll":"M09-10CE29","name":"ADEEL SHAHZAD","shift":"Morning"},
      {"roll":"M09-10CE30","name":"MUHAMMAD AWAIS AKRAM","shift":"Morning"},
      {"roll":"M09-10CE31","name":"HAFIZ MUHAMMAD AWAIS","shift":"Morning"},
      {"roll":"M09-10CE32","name":"MUHAMMAD UMAR FAROOQ","shift":"Morning"},
      {"roll":"M09-10CE33","name":"ZAID KHALID","shift":"Morning"},
      {"roll":"M09-10CE34","name":"HAROON SAEED","shift":"Morning"},
      {"roll":"M09-10CE35","name":"MUHAMMAD USMAN TARIQ","shift":"Morning"},
      {"roll":"M09-10CE36","name":"SAJID JAMEEL JUT","shift":"Morning"},
      {"roll":"M09-10CE37","name":"MUHAMMAD SALEEM","shift":"Morning"},
      {"roll":"M09-10CE38","name":"SAMEE ULLAH","shift":"Morning"},
      {"roll":"M09-10CE39","name":"MUHAMMAD AMJAD MAJEED","shift":"Morning"},
      {"roll":"M09-10CE40","name":"NAZIM HASSAN RIZVI","shift":"Morning"},
      {"roll":"M09-10CE41","name":"SYED AHMAD WAQAS","shift":"Morning"},
      {"roll":"M09-10CE42","name":"HASSAN ABDUR REHMAN","shift":"Morning"},
      {"roll":"M09-10CE43","name":"ANEES UR REHMAN","shift":"Morning"},
      {"roll":"M09-10CE44","name":"ABID MEHMOOD","shift":"Morning"},
      {"roll":"M09-10CE45","name":"WAQAS AHMAD","shift":"Morning"},
      {"roll":"M09-10CE46","name":"USMAN NADEEM","shift":"Morning"},
      {"roll":"M09-10CE47","name":"MUHAMMAD WAQAR","shift":"Morning"},
      {"roll":"M09-10CE48","name":"ARIF JAN","shift":"Morning"},
      {"roll":"M09-10CE49","name":"NAYYER MEHMOOD","shift":"Morning"},
      {"roll":"M09-10CE50","name":"SIDRA ZAHOOR","shift":"Morning"},
      {"roll":"M09-10CE51","name":"QASIM ALI","shift":"Morning"},
      {"roll":"M09-10CE52","name":"MUHAMMAD ZAHID","shift":"Morning"},
      {"roll":"M09-10CE53","name":"JUNAID KHAN","shift":"Morning"},
      {"roll":"M09-10CE54","name":"TAUHID UL HAQ","shift":"Morning"},
      {"roll":"M09-10CE55","name":"QUYYUM FURQAN","shift":"Morning"},
      {"roll":"M09-10CE56","name":"EHTISHAM ALI","shift":"Morning"},
      {"roll":"M09-10PG01","name":"HAFIZ M. SAIF ULLAH SALEEM","shift":"Morning"},
      {"roll":"M09-10PG02","name":"MUHAMMAD AFRAZ","shift":"Morning"},
      {"roll":"M09-10PG03","name":"REHAN ASHRAF","shift":"Morning"},
      {"roll":"M09-10PG04","name":"AFTAB AHMED","shift":"Morning"},
      {"roll":"M09-10PG05","name":"AHMED RIAZ KHAN","shift":"Morning"},
      {"roll":"M09-10PG06","name":"MUHAMMAD ALEEM","shift":"Morning"},
      {"roll":"M09-10PG07","name":"ASMAT ULLAH QAISRANI","shift":"Morning"},
      {"roll":"M09-10PG08","name":"ADEEL HASNAIN","shift":"Morning"},
      {"roll":"M09-10PG09","name":"ILYAS RAZA","shift":"Morning"},
      {"roll":"M09-10PG10","name":"HAFIZ WAQAS WAQAR","shift":"Morning"},
      {"roll":"M09-10PG11","name":"HASSAN QADER","shift":"Morning"},
      {"roll":"M09-10PG12","name":"FARHAN AKHTAR","shift":"Morning"},
      {"roll":"M09-10PG13","name":"GHULAM MURTAZA","shift":"Morning"},
      {"roll":"M09-10PG14","name":"HAFIZ ASAD UR REHMAN","shift":"Morning"},
      {"roll":"M09-10PG15","name":"RIZWAN ASHRAF","shift":"Morning"},
      {"roll":"M09-10PG16","name":"ZUBAIR AHMED KHOKHAR","shift":"Morning"},
      {"roll":"M09-10PG17","name":"AHSAN JALEEL","shift":"Morning"},
      {"roll":"M09-10PG18","name":"MUHAMMAD AYYAZ AMJAD","shift":"Morning"},
      {"roll":"M09-10PG19","name":"MUHAMMAD HABIB SABIR","shift":"Morning"},
      {"roll":"M09-10PG20","name":"MUHAMMAD YOUSAF","shift":"Morning"},
      {"roll":"M09-10PG21","name":"MUHAMMAD MUNEEB SULTAN","shift":"Morning"},
      {"roll":"M09-10PG22","name":"MUHAMMAD SALMAN IJAZ","shift":"Morning"},
      {"roll":"M09-10PG23","name":"ALI AYUB","shift":"Morning"},
      {"roll":"E09-10CE01","name":"MUHAMMAD ARSLAN SARWAR","shift":"Evening"},
      {"roll":"E09-10CE02","name":"MUHAMMAD QASIM","shift":"Evening"},
      {"roll":"E09-10CE03","name":"MUHAMMAD UMAR","shift":"Evening"},
      {"roll":"E09-10CE04","name":"MUHAMMAD ADIL","shift":"Evening"},
      {"roll":"E09-10CE05","name":"MUHAMMAD ABU BAKAR NASIM","shift":"Evening"},
      {"roll":"E09-10CE06","name":"HAMZA AMJAD BUTT","shift":"Evening"},
      {"roll":"E09-10CE07","name":"MUHAMMAD ASIF","shift":"Evening"},
      {"roll":"E09-10CE08","name":"HAFIZ ATA MUHAY-UD DIN","shift":"Evening"},
      {"roll":"E09-10CE09","name":"—","shift":"Evening"},
      {"roll":"E09-10CE10","name":"MUHAMMAD IBRAHEEM SHAH","shift":"Evening"},
      {"roll":"E09-10CE11","name":"MUHAMMAD ANS RIAZ","shift":"Evening"},
      {"roll":"E09-10CE12","name":"MUHAMMAD HARIS","shift":"Evening"},
      {"roll":"E09-10CE13","name":"HAFIZ MUHAMMAD JUNAID KHAN","shift":"Evening"},
      {"roll":"E09-10CE14","name":"KAZAM HUSSAIN GURMANI","shift":"Evening"},
      {"roll":"E09-10CE15","name":"MUHAMMAD UMAIR FAROOQ","shift":"Evening"},
      {"roll":"E09-10CE16","name":"MUHAMMAD ARSHAD KHAN","shift":"Evening"},
      {"roll":"E09-10CE17","name":"MUHAMMAD WAQAS AJMAL","shift":"Evening"},
      {"roll":"E09-10CE18","name":"AIZA NASAR","shift":"Evening"},
      {"roll":"E09-10CE19","name":"RANA MUHAMMAD AQLEEM ULLAH","shift":"Evening"},
      {"roll":"E09-10CE20","name":"FAIZAN AHMED","shift":"Evening"},
      {"roll":"E09-10CE21","name":"ADIL ABBAS","shift":"Evening"},
      {"roll":"E09-10CE22","name":"MUHAMMAD IHSAN UL HAQ","shift":"Evening"},
      {"roll":"E09-10CE23","name":"SIBTAIN KHALID","shift":"Evening"},
      {"roll":"E09-10CE24","name":"MUHAMMAD UBAID HAROON","shift":"Evening"},
      {"roll":"E09-10CE25","name":"ALI WAQAS","shift":"Evening"},
      {"roll":"E09-10CE26","name":"SHAHZEB HASSAN","shift":"Evening"},
      {"roll":"E09-10CE27","name":"—","shift":"Evening"},
      {"roll":"E09-10CE28","name":"MUHAMMAD HASSAN SALEEM","shift":"Evening"},
      {"roll":"E09-10CE29","name":"WAHEED UR REHMAN","shift":"Evening"},
      {"roll":"E09-10CE30","name":"ANAS NADEEM","shift":"Evening"},
      {"roll":"E09-10CE31","name":"UMAIR MAHMOOD","shift":"Evening"},
      {"roll":"E09-10CE32","name":"SHAHID SARFRAZ","shift":"Evening"},
      {"roll":"E09-10CE33","name":"ZIAD AKRAM","shift":"Evening"},
      {"roll":"E09-10CE34","name":"HAFIZ USMAN SAEED","shift":"Evening"},
      {"roll":"E09-10CE35","name":"UMAR FAROOQ","shift":"Evening"},
      {"roll":"E09-10CE36","name":"ABID ALI","shift":"Evening"},
      {"roll":"E09-10CE37","name":"RASHID NAWAZ","shift":"Evening"},
      {"roll":"E09-10CE38","name":"MOHSIN EHSAN BAIG","shift":"Evening"},
      {"roll":"E09-10CE39","name":"MUHAMMAD NASIR","shift":"Evening"},
      {"roll":"E09-10CE40","name":"MUHAMMAD AZEEM SHAUKAT","shift":"Evening"},
      {"roll":"E09-10CE41","name":"ABU BAKAR EJAZ","shift":"Evening"},
      {"roll":"E09-10CE42","name":"UMAIR MAHMOOD BHATTI","shift":"Evening"},
      {"roll":"E09-10CE43","name":"MUHAMMAD IMRAN SAEED","shift":"Evening"},
      {"roll":"E09-10CE44","name":"HAFIZ ABUZAR AHSAN","shift":"Evening"},
      {"roll":"E09-10CE45","name":"M. MOHSIN ANWAR","shift":"Evening"},
      {"roll":"E09-10CE46","name":"SHUJA UR REHMAN","shift":"Evening"},
      {"roll":"E09-10CE47","name":"MUHAMMAD SABTAIN","shift":"Evening"},
      {"roll":"E09-10PG01","name":"HASSAN BIN WAHEED","shift":"Evening"},
      {"roll":"E09-10PG02","name":"MUHAMMAD SAJID QAMAR","shift":"Evening"},
      {"roll":"E09-10PG03","name":"MUHAMMAD KAMRAN HAIDER","shift":"Evening"},
      {"roll":"E09-10PG04","name":"SOHAIB MUSHTAQ","shift":"Evening"},
      {"roll":"E09-10PG05","name":"MUHAMMAD ASIM BABAR","shift":"Evening"},
      {"roll":"E09-10PG06","name":"YASHIB YOUSAF KAMRAN SAROIA","shift":"Evening"},
      {"roll":"E09-10PG07","name":"IRFAN YOUSAF","shift":"Evening"},
      {"roll":"E09-10PG08","name":"SYED ALI AQDUS SHAH","shift":"Evening"},
      {"roll":"E09-10PG09","name":"HAFIZ MUHAMMAD FAHAD ILYAS","shift":"Evening"},
      {"roll":"E09-10PG10","name":"MUHAMMAD JAWAD","shift":"Evening"},
      {"roll":"E09-10PG11","name":"AQSA HASSAN","shift":"Evening"},
      {"roll":"E09-10PG12","name":"MUHAMMAD ATIF ILYAS","shift":"Evening"},
      {"roll":"E09-10PG13","name":"SAIF UR REHMAN","shift":"Evening"}
    ]
  },

  '2016': {
    label: 'Session 2016–2020',
    total: 107, morning: 61, evening: 46,
    whatsapp: '',   // paste group invite link here when available
    active: true,
    members: [
      {"roll":"RP16-CE01","name":"MUHAMMAD QASIM RIAZ","shift":"Morning"},
      {"roll":"RP16-CE02","name":"ARBAB NOOR","shift":"Morning"},
      {"roll":"RP16-CE03","name":"ZILL E HUMA SALEEM","shift":"Morning"},
      {"roll":"RP16-CE04","name":"REEBAHA ASHRAF","shift":"Morning"},
      {"roll":"RP16-CE05","name":"HAMZA TAHIR","shift":"Morning"},
      {"roll":"RP16-CE06","name":"HAFIZ ABDUL REHMAN","shift":"Morning"},
      {"roll":"RP16-CE07","name":"HAMNA SHAHID","shift":"Morning"},
      {"roll":"RP16-CE08","name":"WANIA NOUREEN","shift":"Morning"},
      {"roll":"RP16-CE09","name":"FAISAL MEHMOOD","shift":"Morning"},
      {"roll":"RP16-CE10","name":"MUHAMMAD AHMAD NASEEM","shift":"Morning"},
      {"roll":"RP16-CE11","name":"MUHAMMAD ADNAN","shift":"Morning"},
      {"roll":"RP16-CE12","name":"HAFIZ MUHAMMAD HASSAN ABID","shift":"Morning"},
      {"roll":"RP16-CE13","name":"WAQAR AHMAD ALI","shift":"Morning"},
      {"roll":"RP16-CE14","name":"UMBREEN ZOHRA","shift":"Morning"},
      {"roll":"RP16-CE15","name":"EEMAN NAVEED","shift":"Morning"},
      {"roll":"RP16-CE16","name":"MUHAMMAD IMTIAZ","shift":"Morning"},
      {"roll":"RP16-CE17","name":"AHMAD SALEEM","shift":"Morning"},
      {"roll":"RP16-CE18","name":"MUHAMMAD MINHAJ QADRI","shift":"Morning"},
      {"roll":"RP16-CE19","name":"MUHAMAD EHSAN ELAHI","shift":"Morning"},
      {"roll":"RP16-CE20","name":"MUHAMMAD USAMA","shift":"Morning"},
      {"roll":"RP16-CE21","name":"AYESHA SHAHBAZ","shift":"Morning"},
      {"roll":"RP16-CE22","name":"AHSAN ALI","shift":"Morning"},
      {"roll":"RP16-CE23","name":"HAMZA BIN AZAM","shift":"Morning"},
      {"roll":"RP16-CE24","name":"MUHAMMAD AHMAD HASSAN","shift":"Morning"},
      {"roll":"RP16-CE25","name":"MUHAMMAD IQBAL","shift":"Morning"},
      {"roll":"RP16-CE26","name":"MUHAMMAD TALHA FAROOQ","shift":"Morning"},
      {"roll":"RP16-CE27","name":"MAHNOOR RIAZ","shift":"Morning"},
      {"roll":"RP16-CE28","name":"AMINA IQBAL","shift":"Morning"},
      {"roll":"RP16-CE29","name":"RANA BILAL HAKEEM","shift":"Morning"},
      {"roll":"RP16-CE30","name":"TALHA AHMAD","shift":"Morning"},
      {"roll":"RP16-CE31","name":"MUHAMMAD ASIF","shift":"Morning"},
      {"roll":"RP16-CE32","name":"SHAHZEB FAROOQ","shift":"Morning"},
      {"roll":"RP16-CE33","name":"MUHAMMAD USAMA","shift":"Morning"},
      {"roll":"RP16-CE34","name":"RAJA MUHAMMAD MURTAZA","shift":"Morning"},
      {"roll":"RP16-CE35","name":"ZAINAB DAWOOD","shift":"Morning"},
      {"roll":"RP16-CE36","name":"MUHAMMAD OLYAN","shift":"Morning"},
      {"roll":"RP16-CE37","name":"MUHAMMAD ALI ASHRAF","shift":"Morning"},
      {"roll":"RP16-CE38","name":"QURBAN ALI","shift":"Morning"},
      {"roll":"RP16-CE39","name":"SUNDAS ALI","shift":"Morning"},
      {"roll":"RP16-CE40","name":"SHAH FAISAL","shift":"Morning"},
      {"roll":"RP16-CE41","name":"MUHAMMAD ILYAS KHAN","shift":"Morning"},
      {"roll":"RP16-CE42","name":"DANIYAL","shift":"Morning"},
      {"roll":"RP16-CE43","name":"MUHAMMAD RIZWAN","shift":"Morning"},
      {"roll":"RP16-CE44","name":"HOSAM ELDEIN TARIQ OSMAN ADAM","shift":"Morning"},
      {"roll":"RP16-CE45","name":"ARSAL AFTAB KHAN","shift":"Morning"},
      {"roll":"RP16-PG01","name":"MUHAMMAD SALMAN","shift":"Morning"},
      {"roll":"RP16-PG02","name":"MUHAMMAD ABID","shift":"Morning"},
      {"roll":"RP16-PG03","name":"MIAN MUHAMMAD MAHAD NASIR","shift":"Morning"},
      {"roll":"RP16-PG04","name":"TABEDAR MUSTAFA","shift":"Morning"},
      {"roll":"RP16-PG05","name":"MUHAMMAD BILAL","shift":"Morning"},
      {"roll":"RP16-PG06","name":"MUHAMMAD SUFYAN BUTT","shift":"Morning"},
      {"roll":"RP16-PG07","name":"MUHAMMAD RIZWAN","shift":"Morning"},
      {"roll":"RP16-PG08","name":"MUHAMMAD ZAMAN","shift":"Morning"},
      {"roll":"RP16-PG09","name":"JAZAB YASEEN","shift":"Morning"},
      {"roll":"RP16-PG10","name":"MUZAMMIL AHMAD","shift":"Morning"},
      {"roll":"RP16-PG11","name":"BILAL ISLAM","shift":"Morning"},
      {"roll":"RP16-PG12","name":"MUHAMMAD KHURRAM NAWAZ","shift":"Morning"},
      {"roll":"RP16-PG13","name":"HAFIZ MUHAMMAD ESSA","shift":"Morning"},
      {"roll":"RP16-PG14","name":"MUHAMMAD FARHAN SHAHID","shift":"Morning"},
      {"roll":"RP16-PG15","name":"EHTISHAM ALI AZAD","shift":"Morning"},
      {"roll":"RP16-PG16","name":"WAJI UL HASSAN KIANI","shift":"Morning"},
      {"roll":"SSP16-CE01","name":"SUBIYAL MIRZA","shift":"Evening"},
      {"roll":"SSP16-CE02","name":"UMER BIN UBAID","shift":"Evening"},
      {"roll":"SSP16-CE03","name":"MAHNOOR SYED","shift":"Evening"},
      {"roll":"SSP16-CE04","name":"MUHAMMAD HUZAIFA","shift":"Evening"},
      {"roll":"SSP16-CE05","name":"MUHAMMAD AJMAL ROUF","shift":"Evening"},
      {"roll":"SSP16-CE06","name":"MUHAMMAD HUZAIFA SOHAIL","shift":"Evening"},
      {"roll":"SSP16-CE07","name":"MUHAMMAD TAHIR JUNAID","shift":"Evening"},
      {"roll":"SSP16-CE08","name":"AMEER HAMZA","shift":"Evening"},
      {"roll":"SSP16-CE09","name":"ARSLAN KHAN","shift":"Evening"},
      {"roll":"SSP16-CE10","name":"AYESHA ZULFIQAR","shift":"Evening"},
      {"roll":"SSP16-CE11","name":"URWA AQUEEL","shift":"Evening"},
      {"roll":"SSP16-CE12","name":"AHMED ALI","shift":"Evening"},
      {"roll":"SSP16-CE13","name":"UMER FAROOQ","shift":"Evening"},
      {"roll":"SSP16-CE14","name":"MISRA TAHIR","shift":"Evening"},
      {"roll":"SSP16-CE15","name":"SHABBIR AHMAD","shift":"Evening"},
      {"roll":"SSP16-CE16","name":"TALHA BIN SHAKEEL","shift":"Evening"},
      {"roll":"SSP16-CE17","name":"SIBGHAT ULLAH","shift":"Evening"},
      {"roll":"SSP16-CE18","name":"KIRAN ASGHER","shift":"Evening"},
      {"roll":"SSP16-CE19","name":"HAFIZ MUHAMMAD FARHAN YASIN","shift":"Evening"},
      {"roll":"SSP16-CE20","name":"HAMMAD KHALID","shift":"Evening"},
      {"roll":"SSP16-CE21","name":"HASIN KHALID","shift":"Evening"},
      {"roll":"SSP16-CE22","name":"HAFIZ MUHAMMAD HARIS","shift":"Evening"},
      {"roll":"SSP16-CE23","name":"SANA ARBAB","shift":"Evening"},
      {"roll":"SSP16-CE24","name":"MUHAMMAD TAHA KHAN","shift":"Evening"},
      {"roll":"SSP16-CE25","name":"SYED GHAZANFAR ALI","shift":"Evening"},
      {"roll":"SSP16-CE26","name":"SYED MUHAMMAD ALI BAQIR","shift":"Evening"},
      {"roll":"SSP16-CE27","name":"MUHAMMAD MUNEEB","shift":"Evening"},
      {"roll":"SSP16-CE28","name":"MUHAMMAD UMER","shift":"Evening"},
      {"roll":"SSP16-CE29","name":"KHALIL AHMAD","shift":"Evening"},
      {"roll":"SSP16-CE30","name":"MAKHDOOM JAWAD ULLAH","shift":"Evening"},
      {"roll":"SSP16-CE31","name":"SUFYAN AHMED","shift":"Evening"},
      {"roll":"SSP16-PG01","name":"MUDASSAR ARSHAD","shift":"Evening"},
      {"roll":"SSP16-PG02","name":"SADAQAT ALI","shift":"Evening"},
      {"roll":"SSP16-PG03","name":"ANS IRSHAD","shift":"Evening"},
      {"roll":"SSP16-PG04","name":"MUHAMMAD OSSAMA","shift":"Evening"},
      {"roll":"SSP16-PG05","name":"SYED MUHAMMAD HASSAN YOUSUF","shift":"Evening"},
      {"roll":"SSP16-PG06","name":"MUHAMMAD ANS BIN AQEEL","shift":"Evening"},
      {"roll":"SSP16-PG07","name":"SARDAR MUHAMMAD ASAD HAYAT","shift":"Evening"},
      {"roll":"SSP16-PG08","name":"ASFAR HUSSAIN KHAN","shift":"Evening"},
      {"roll":"SSP16-PG09","name":"ALI RASHID","shift":"Evening"},
      {"roll":"SSP16-PG10","name":"MOBEEN IRFAN","shift":"Evening"},
      {"roll":"SSP16-PG11","name":"MUNEEB UR REHMAN","shift":"Evening"},
      {"roll":"SSP16-PG12","name":"MUHAMMAD UMER RANA","shift":"Evening"},
      {"roll":"SSP16-PG13","name":"AMNA SAEED","shift":"Evening"},
      {"roll":"SSP16-PG14","name":"HASSAM QAISER","shift":"Evening"},
      {"roll":"SSP16-PG15","name":"RASHEED AHMAD","shift":"Evening"}
    ]
  },

  // ── Inactive sessions (coming soon) ──────────────────────────────────────
  '2000': { label: 'Session 2000–2004', total: 0, morning: 0, evening: 0, active: false, members: [] },
  '2001': { label: 'Session 2001–2005', total: 0, morning: 0, evening: 0, active: false, members: [] },
  '2002': { label: 'Session 2002–2006', total: 0, morning: 0, evening: 0, active: false, members: [] },
  '2003': { label: 'Session 2003–2007', total: 0, morning: 0, evening: 0, active: false, members: [] },
  '2004': { label: 'Session 2004–2008', total: 0, morning: 0, evening: 0, active: false, members: [] },
  '2005': { label: 'Session 2005–2009', total: 0, morning: 0, evening: 0, active: false, members: [] },
  '2007': { label: 'Session 2007–2011', total: 0, morning: 0, evening: 0, active: false, members: [] },
  '2008': { label: 'Session 2008–2012', total: 0, morning: 0, evening: 0, active: false, members: [] },
  '2010': { label: 'Session 2010–2014', total: 0, morning: 0, evening: 0, active: false, members: [] },
  '2011': { label: 'Session 2011–2015', total: 0, morning: 0, evening: 0, active: false, members: [] },
  '2012': { label: 'Session 2012–2016', total: 0, morning: 0, evening: 0, active: false, members: [] },
  '2013': { label: 'Session 2013–2017', total: 0, morning: 0, evening: 0, active: false, members: [] },
  '2014': { label: 'Session 2014–2018', total: 0, morning: 0, evening: 0, active: false, members: [] },
  '2015': { label: 'Session 2015–2019', total: 0, morning: 0, evening: 0, active: false, members: [] },
  '2017': { label: 'Session 2017–2021', total: 0, morning: 0, evening: 0, active: false, members: [] },
  '2018': { label: 'Session 2018–2022', total: 0, morning: 0, evening: 0, active: false, members: [] },
  '2019': { label: 'Session 2019–2023', total: 0, morning: 0, evening: 0, active: false, members: [] },
  '2020': { label: 'Session 2020–2024', total: 0, morning: 0, evening: 0, active: false, members: [] },
  '2021': { label: 'Session 2021–2025', total: 0, morning: 0, evening: 0, active: false, members: [] },
  '2022': { label: 'Session 2022–2026', total: 0, morning: 0, evening: 0, active: false, members: [] },
};
